name: cw-scheduler
recipe: drupal8
config:
  webroot: web
  php: 7.2
  xdebug: false
  conf:
    php: dev/php.ini
    mysql: /dev/my.cnf
services:
  database:
    type: mariadb
    portforward: 3350
  pma:
    type: phpmyadmin
    hosts:
      - database
  appserver:
    composer:
      phpunit/phpunit: '*'
      behat/behat: 3.3.1
  node:
    type: node:6.10
    globals:
      gulp-cli: latest
    build:
      - "cd $LANDO_MOUNT && npm install"
tooling:
  phpunit:
    service: appserver
    description: run PHPUnit- use lando phpunit
  behat:
    service: appserver
    description: run behat- use lando behat
  node:
    service: node
  npm:
    service: node
  gulp:
    service: node
