name: cw-scheduler
recipe: drupal8
config:
  webroot: web
  php: 7.2
  xdebug: false
  conf:
    php: dev/php.ini
    mysql: dev/my.cnf
services:
  database:
    type: mariadb
    portforward: 3350
  pma:
    type: phpmyadmin
    hosts:
      - database
  node:
    type: node:6.10
    globals:
      gulp-cli: latest
    build:
      - cd $LANDO_MOUNT && npm install
  appserver:
    composer:
      phpunit/phpunit: '*'
      behat/behat: 3.3.1
    build:
      - |
        if [ -n "$GITHUB_TOKEN" ] ; then
          cd $LANDO_MOUNT && composer config --global --auth --unset github-oauth.github.com && composer config --global github-oauth.github.com $GITHUB_TOKEN
        fi
tooling:
  phpunit:
    service: appserver
    description: run PHPUnit- use lando phpunit
  behat:
    service: appserver
    description: run behat- use lando behat
  node:
    service: node
  npm:
    service: node
  gulp:
    service: node
